//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiYiJiShu.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public int DoctorID { get; set; }
        public string DoctorName { get; set; }
        public string DoctorJobTitle { get; set; }
        public string DoctorCompany { get; set; }
        public Nullable<int> DoctorType { get; set; }
        public Nullable<int> FirstClassID { get; set; }
        public string FirstClassName { get; set; }
        public Nullable<int> SecondClassID { get; set; }
        public string SecondClassName { get; set; }
        public string ProvinceID { get; set; }
        public string DoctorPic { get; set; }
        public string DoctorIntro { get; set; }
        public string DoctorMajor { get; set; }
        public string DoctorAchievement { get; set; }
        public Nullable<int> HitCount { get; set; }
        public Nullable<System.DateTime> EditDateTime { get; set; }
        public Nullable<int> TuiJian { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ActiveFlag { get; set; }
    }
}
