//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiYiJiShu.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JiDiJianShe
    {
        public int JiDiId { get; set; }
        public string JiDiName { get; set; }
        public string JiDiCompany { get; set; }
        public string JiDiLeader { get; set; }
        public string JiDiJobContent { get; set; }
        public string JiDiIntro { get; set; }
        public string JiDiPic { get; set; }
        public Nullable<System.DateTime> AddDateTime { get; set; }
        public Nullable<int> FirstClassID { get; set; }
        public Nullable<int> SecondClassID { get; set; }
        public Nullable<int> ActiveFlag { get; set; }
        public Nullable<int> TuiJian { get; set; }
        public Nullable<int> HitCount { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
