//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiYiJiShu.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int JobID { get; set; }
        public string JobTitle { get; set; }
        public Nullable<System.DateTime> JobPublishDate { get; set; }
        public Nullable<System.DateTime> JobEndDate { get; set; }
        public string JobHeadCount { get; set; }
        public string JobAddress { get; set; }
        public string JobWorkingYear { get; set; }
        public string JobEducation { get; set; }
        public string JobFunction { get; set; }
        public string JobDescription { get; set; }
        public Nullable<int> ZhiDing { get; set; }
        public Nullable<int> HitCount { get; set; }
    }
}
