//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiYiJiShu.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShiYiJiShuEntities : DbContext
    {
        public ShiYiJiShuEntities()
            : base("name=ShiYiJiShuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminUser> AdminUsers { get; set; }
        public virtual DbSet<Certificate> Certificates { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<FocusPic> FocusPics { get; set; }
        public virtual DbSet<FriendLink> FriendLinks { get; set; }
        public virtual DbSet<Info> Infoes { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<NewsClass> NewsClasses { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Technology> Technologies { get; set; }
        public virtual DbSet<Video> Videos { get; set; }
        public virtual DbSet<VoteLog> VoteLogs { get; set; }
        public virtual DbSet<VoteStaff> VoteStaffs { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<ProjectRegister> ProjectRegisters { get; set; }
        public virtual DbSet<JiDiJianShe> JiDiJianShes { get; set; }
    }
}
