//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiYiJiShu.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsClass
    {
        public int ClassID { get; set; }
        public string ClassName { get; set; }
        public Nullable<int> ClassLevel { get; set; }
        public Nullable<int> ParentClassID { get; set; }
        public string ClassType { get; set; }
        public string Keyword { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
