//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiYiJiShu.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectRegister
    {
        public int RegID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string UserName { get; set; }
        public string Mobile { get; set; }
        public string UserEmail { get; set; }
        public string UserCompany { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> RegDateTime { get; set; }
    }
}
