//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiYiJiShu.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelectProject
    {
        public int ProjectId { get; set; }
        public string ProjectName { get; set; }
        public string ProjectCompany { get; set; }
        public string ProjectLeader { get; set; }
        public string ProjectIntro { get; set; }
        public string ProjectContent { get; set; }
        public string ProjectPic { get; set; }
        public string ProjectLink { get; set; }
        public Nullable<int> FirstClassID { get; set; }
        public Nullable<int> SecondClassID { get; set; }
        public Nullable<int> ActiveFlag { get; set; }
        public Nullable<int> TuiJian { get; set; }
        public Nullable<int> ZhiDing { get; set; }
        public Nullable<int> HitCount { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> AddDateTime { get; set; }
    }
}
