//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiYiJiShu.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoteStaff
    {
        public int StaffID { get; set; }
        public string StaffName { get; set; }
        public string StaffDetail { get; set; }
        public string StaffPhoto { get; set; }
        public string Company { get; set; }
        public Nullable<System.DateTime> AddDateTime { get; set; }
        public Nullable<int> VoteCount { get; set; }
        public string JobTitle { get; set; }
        public string TechName { get; set; }
        public string LinkUrl { get; set; }
        public Nullable<int> FirstClassID { get; set; }
        public Nullable<int> SecondClassID { get; set; }
    }
}
